// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnDu0pFPmH3PGJPlES2ycPCqqttyNDa8',
    appId: '1:520117589885:web:cd814e1fc3f36a51d5de14',
    messagingSenderId: '520117589885',
    projectId: 'travel-planner-94220',
    authDomain: 'travel-planner-94220.firebaseapp.com',
    storageBucket: 'travel-planner-94220.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrb1PB94odw461rLAZb7HWEBteL3hVpc',
    appId: '1:520117589885:android:c192625773d47461d5de14',
    messagingSenderId: '520117589885',
    projectId: 'travel-planner-94220',
    storageBucket: 'travel-planner-94220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_-slNz0yc7zK6MnESfpEcg5DX8pU39E',
    appId: '1:520117589885:ios:80069509e5dbfcd7d5de14',
    messagingSenderId: '520117589885',
    projectId: 'travel-planner-94220',
    storageBucket: 'travel-planner-94220.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_-slNz0yc7zK6MnESfpEcg5DX8pU39E',
    appId: '1:520117589885:ios:80069509e5dbfcd7d5de14',
    messagingSenderId: '520117589885',
    projectId: 'travel-planner-94220',
    storageBucket: 'travel-planner-94220.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcnDu0pFPmH3PGJPlES2ycPCqqttyNDa8',
    appId: '1:520117589885:web:fce67aeb9914c82ed5de14',
    messagingSenderId: '520117589885',
    projectId: 'travel-planner-94220',
    authDomain: 'travel-planner-94220.firebaseapp.com',
    storageBucket: 'travel-planner-94220.firebasestorage.app',
  );
}
